### ISSUE TITLE
Unable to install with docker

### ISSUE THREAD

**Issue by triptronics** [Bottelet/DaybydayCRM#198]
Hello, I have attempted to install via docker following the instructions but I'm having an issue.

![Capture](https://user-images.githubusercontent.com/44954029/98430113-54287000-2079-11eb-9f5a-02d434f80fc4.JPG)

That happens after I run: sudo docker-compose exec php composer install

Seems like a permissions issue maybe, not sure. Please help, thanks!

**Comment by rm-yakovenko** [comment]
Hello @triptronics.

Could you try the following steps:
```
mkdir vendor
chmod a+w vendor
docker-compose build php
docker-compose exec php composer install
```
Internally, the docker container runs as the user with id 1000. Looks like the code was cloned by a user with a different id. That's why it cannot create the vendor folder and fails. The above steps should fix the issue, but I'm not sure that it's the best solution.

**Comment by Bottelet** [comment]
@triptronics 
Did you figure it out? If not please reopen the issue
