### ISSUE TITLE
Error - task list - tasks without assigned project

### ISSUE THREAD

**Issue by marohds** [Bottelet/DaybydayCRM#217]
Hi, 
This is my first try of DaybydayCRM.

I've found that Task List throws an error when there are tasks without assigned project.

[23:19:02] LOG.error: ErrorException: Trying to get property 'company_name' of non-object in .../Flarepoint-crm/app/Http/Controllers/TasksController.php:69

Regards

**Comment by rm-yakovenko** [comment]
Hello!

It looks like this issue has been fixed in the **develop** branch but still exists in the **master** branch (https://github.com/Bottelet/DaybydayCRM/commit/2a284a19000264020b4f667ffbec29003734d41e#diff-02366b87a11c4c84a4ddcae1877d827ad8e69433198115cee3eb48a5572cc450L72). 

As a temporary workaround, you could apply this patch.

[217_Error_-_task_list_-_tasks_without_assigned_project.patch.zip](https://github.com/Bottelet/DaybydayCRM/files/5764391/217_Error_-_task_list_-_tasks_without_assigned_project.patch.zip)

**Comment by Bottelet** [comment]
Hi @rm-yakovenko Where do you see this in develop, but not master? 

Master should be in front as I am gonna deprecate, develop soon. 

Cheers

**Comment by rm-yakovenko** [comment]
Hi @Bottelet.

Looks like the issue still exists and needs to be fixed.

This error occurs in `TasksController.php` in the following code:
https://github.com/Bottelet/DaybydayCRM/blob/c55491a30b8d7cf165d402878c3dd6aed9ca2f04/app/Http/Controllers/TasksController.php#L68-L70

But in the **develop** branch, there's no `client` column. That's why it's not thrown there.

`->editColumn('client', function ($projects)` is only present in the **master** branch and not present in the **develop** branch [develop..master](https://github.com/Bottelet/DaybydayCRM/compare/develop...master#diff-02366b87a11c4c84a4ddcae1877d827ad8e69433198115cee3eb48a5572cc450R68-R70). 

Looks like the commit, that adds the `client` column, only exists in the **master** branch. 

My guess about fixing this issue in **develop** was not correct.

**Comment by marohds** [comment]
Hi @Bottelet, @rm-yakovenko 

First of all, thank you for your time.

I've had that error because I tried to have a Project without assigning it to clients.

I couldn't find any documentation that leads me to use Project-Client-Task relations. So i've started to probe and guess how to use these, because i'm new at CRM standars too.

My intention is to have one or more contextual projects so I can link multiple new clients made because each one...

More precisely, the next project is for raising my clients: 
 - I'm trying to have a project named "Make 10 clients via phone call this week"
 - So, I'll relate every client made by phone call to this same project.
 - Later, I will know what was my performance within this project.

Another example, the next project is for raising my sells on clients in the same region: 
 - I'm trying to have a project named "Sell more than 100k each client in the next month".
 - In the project notes, I may define many leads for and special offers...
 - Then I'll relate many clients to the same project.
 - Later, I will know what was my performance within this project.

The thing is that in these scenarios, it's not wright to have a Project - Single Client relation. So the client_id field in the project table is not useful.

So I guess there may be worthy to review the usage of that field and the need to have a Project-Single Client relation in the master branch.

Regards

**Comment by Bottelet** [comment]
This has been fixed by @rm-yakovenko Thanks!
